name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm -v 
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env: 
          CI: true